load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test", "go_binary")

filegroup(
    name = "templates",
    srcs = glob([
        "*.tmpl",
    ]),
    visibility = ["//visibility:public"],
)
